### ISSUE TITLE
Add Docker docs

### ISSUE THREAD

**Issue by machawk1** [metadata-research/yamz#157]
The repo has a Dockerfile. How does one use it? Let's add documentation. If it's unstable/unreliable, it would be worthwhile to mention this as well.

**Comment by machawk1** [comment]
For example, it references a `yamz.sql`, which does not exist in the repo. I believe I discussed this file with @cr625 in the past.

**Comment by machawk1** [comment]
An old commit https://github.com/metadata-research/yamz/tree/778566e10eadf2e2eeddd7ad859f96df11b423c8 has a yamz.sql file but it has since been deleted.

**Comment by machawk1** [comment]
Updated the config file reference in 286e5ba665d5aa5d8cb02ebbbe930c1e30a051b9 . Pushed straight to main, as it should not affect anything else.

**Comment by machawk1** [comment]
psycopg2-binary installation seems to be an issue. I updated the requirements file to use the latest (v. 2.9.9) of the module and the Dockerfile builds.

**Comment by cr625** [comment]
The outstanding issue involves the yamz.sql file, which is a backup of the yamz terms exported from the database (as described in the readme). Without that file there is just an empty copy of the flask app that runs but doesn't do anything so we were going to decide what the docker distro would include as terms.

**Comment by machawk1** [comment]
@cr625 I believe it would be good for the project to supply _some_ sample data just to allow the user to test the base functionality of the app -- even if it's not a dump from the prod db.

**Comment by machawk1** [comment]
Sourcing the old yamz.sql file is a little problematic. After I build the image:

`docker build -t yamz .`

...then run the container with port mapping (`5000` is a conflict):

`docker run -p 5001:5000 yamz`

...click browse then a term, I get an error when accessing the term on the web:

```
[2024-05-22 16:28:50,784] ERROR in app: Exception on /term/alternates/user community [GET]
Traceback (most recent call last):
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column terms.search_vector does not exist
LINE 1: ...S terms_concept_id, terms.status AS terms_status, terms.sear...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/yamz/app/term/views.py", line 130, in show_alternate_terms
    return render_template(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/yamz/app/term/templates/term/display_terms.jinja", line 1, in top-level template code
    {% extends './base.jinja' %}
  File "/yamz/app/templates/base.jinja", line 115, in top-level template code
    {% block content %}
  File "/yamz/app/term/templates/term/display_terms.jinja", line 22, in block 'content'
    {% for selected_term in selected_terms  %}
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2900, in __iter__
    return self._iter().__iter__()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column terms.search_vector does not exist
LINE 1: ...S terms_concept_id, terms.status AS terms_status, terms.sear...
                                                             ^

[SQL: SELECT terms.class AS terms_class, terms.id AS terms_id, terms.ark_id AS terms_ark_id, terms.shoulder AS terms_shoulder, terms.naan AS terms_naan, terms.owner_id AS terms_owner_id, terms.created AS terms_created, terms.modified AS terms_modified, terms.term_string AS terms_term_string, terms.definition AS terms_definition, terms.definition_html AS terms_definition_html, terms.examples AS terms_examples, terms.examples_html AS terms_examples_html, terms.concept_id AS terms_concept_id, terms.status AS terms_status, terms.search_vector AS terms_search_vector 
FROM terms 
WHERE terms.term_string = %(term_string_1)s AND terms.status = %(status_1)s]
[parameters: {'term_string_1': 'user community', 'status_1': 'published'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Exception on /term/alternates/user community [GET]
Traceback (most recent call last):
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column terms.search_vector does not exist
LINE 1: ...S terms_concept_id, terms.status AS terms_status, terms.sear...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/yamz/app/term/views.py", line 130, in show_alternate_terms
    return render_template(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/yamz/app/term/templates/term/display_terms.jinja", line 1, in top-level template code
    {% extends './base.jinja' %}
  File "/yamz/app/templates/base.jinja", line 115, in top-level template code
    {% block content %}
  File "/yamz/app/term/templates/term/display_terms.jinja", line 22, in block 'content'
    {% for selected_term in selected_terms  %}
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2900, in __iter__
    return self._iter().__iter__()
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/var/lib/postgresql/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column terms.search_vector does not exist
LINE 1: ...S terms_concept_id, terms.status AS terms_status, terms.sear...
                                                             ^

[SQL: SELECT terms.class AS terms_class, terms.id AS terms_id, terms.ark_id AS terms_ark_id, terms.shoulder AS terms_shoulder, terms.naan AS terms_naan, terms.owner_id AS terms_owner_id, terms.created AS terms_created, terms.modified AS terms_modified, terms.term_string AS terms_term_string, terms.definition AS terms_definition, terms.definition_html AS terms_definition_html, terms.examples AS terms_examples, terms.examples_html AS terms_examples_html, terms.concept_id AS terms_concept_id, terms.status AS terms_status, terms.search_vector AS terms_search_vector 
FROM terms 
WHERE terms.term_string = %(term_string_1)s AND terms.status = %(status_1)s]
[parameters: {'term_string_1': 'user community', 'status_1': 'published'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
172.17.0.1 - - [22/May/2024 16:28:50] "GET /term/alternates/user%20community HTTP/1.1" 500 -
172.17.0.1 - - [22/May/2024 16:28:50] "GET /static/css/site.css HTTP/1.1" 304 -
172.17.0.1 - - [22/May/2024 16:28:50] "GET /static/images/yamz_purple_logo_square_small.png HTTP/1.1" 304 -
172.17.0.1 - - [22/May/2024 16:28:50] "GET /static/images/favicon.ico HTTP/1.1" 304
```

Perhaps this is attributed to the code expecting some different DB structure than what is provided in the old yamz.sql. A fresh, usable dump of yamz.sql would be good to have for testing. Can this be generated from production and perhaps pared down to test the fundamentals?

**Comment by cr625** [comment]
> Perhaps this is attributed to the code expecting some different DB structure than what is provided in the old yamz.sql. A fresh, usable dump of yamz.sql would be good to have for testing. Can this be generated from production and perhaps pared down to test the fundamentals?

We did change the columns, you're right to add [search_vector](https://github.com/metadata-research/yamz/blob/d1850853269a5d745f3c9876918df50145390750/app/term/models.py#L103). We could generate the dump file from a subset. I think the simplest way is to pick a filter and export only those terms. For example, we could choose the NASA helio data as our sample data or something from material science. The other option I think would be to generate a test set but that is time consuming, I'm sure.

**Comment by machawk1** [comment]
@cr625 Extracting a subset from production (e.g., helio) would be a good start. If it's not to much trouble, please do so.

**Comment by machawk1** [comment]
@cr625 Can you supply the command you were using on the prod server to obtain the backup?

I do not believe I have credentials for that server. Obtaining a dump that aligns with the current main branch code is a blocker for this GitHub issue.

**Comment by machawk1** [comment]
I began stripping out a yamz.sql based on the above just to get up and running and have added that to the `issue-157` branch. It would be far less laborious and more accurate to the implementation to have a modern dump that aligns with the prod db schema.

**Comment by machawk1** [comment]
@jkunze Provided a dump from prod from July 29, 2025. It currently resides in the private https://github.com/metadata-research/yamz-data repo for testing.
